version: '3.2'


services:
  nftnginx:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    env_file:
      - ./.envs/.frontend
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80"
    networks:
      - demo_nft_network
  
  backend:
    build:
      context: ./server/
    ports:
      - "8000"
    restart: always
    env_file:
      - ./.envs/.backend
    networks:
      - demo_nft_network

 
networks:
  demo_nft_network:
    driver: bridge