version: '3.2'


services:
  nginx:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    environment:
      - REACT_APP_OWNER_CONTRACT=0x226a29337f00ceba61d2fb7305e697981ec60f27
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - demo_nft_network
  
  backend:
    build:
      context: ./server/
    ports:
      - "8000"
    restart: always
    environment:
      - SIGNER_SALT=batonis.nft
      - SIGNER_PRIVATE_KEY=d02588543a46c7c511e61d50df63e81ff0d22c1482bed9be84800d6b37fb0eb9
      - PORT=8000
    networks:
      - demo_nft_network

 
networks:
  demo_nft_network:
    driver: bridge